[package]
name = "tontuna-lsp"
version = "0.1.0"
edition = "2018"

[dependencies]
lsp-server = "0.5.2"
lsp-types = "0.89.2"
serde = "1.0.127"
serde_json = "1.0.66"
crossbeam-channel = "0.5.1"
tontuna = { path = "../tontuna" }
